[package]
name = "crescent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
axum = "0.8.1"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
